
public class Test3 extends javax.swing.JFrame {
    String info[][];
    
   
    public Test3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsearch = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtoutput = new javax.swing.JTextArea();
        txtmovie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");

        txtoutput.setColumns(20);
        txtoutput.setRows(5);
        jScrollPane1.setViewportView(txtoutput);

        txtmovie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsearch)
                        .addGap(92, 92, 92)
                        .addComponent(btnclear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtmovie))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(btnclear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        info = fillData();
        String movie;
        movie=txtmovie.getText();
        String times[]= getTimes(info,movie);
        txtoutput.setText("The times are: ");
        for(int x=0; x<times.length; x++){
            txtoutput.append("\n"+times[x]);
        }
        
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtmovie.setText("");
        txtoutput.setText("");
    }//GEN-LAST:event_btnclearActionPerformed
    
    public String[] getTimes(String m[][],String mov){
        int num=0;
        for (int x=0; x<m.length; x++){
            if(m[x][1].equals(mov)){
                num++;   
            }
        }
        String times[]=new String[num];
        num=0;
        for (int y=0; y<m.length; y++){
            if(m[y][1].equals(mov)){
                times[num]=m[y][0];
                num++;
            }
        }
        return times;
    }
    
    public String[][] fillData(){

	String data[][]=new String[][]
	{
		{"Galaxy-10 pm","Life of Pi"},
		{"Galaxy-7 pm","GI Joe"},
		{"Galaxy-10 pm","The Host"},
		{"Galaxy-7 pm","GI Joe"},
		{"Galaxy-8 pm","GI Joe"},
		{"Uptown-5 pm","Oblivion"},
		{"Galaxy-9 pm","The Host"},
		{"Bayfield-8 pm","Life of Pi"},
		{"Galaxy-1 pm","The Host"},
		{"Galaxy-3 pm","Silver Lining"},
		{"Bayfield-5 pm","GI Joe"},
		{"Uptown-6 pm","The Host"},
		{"Galaxy-7 pm","The Host"},
		{"Galaxy-5 pm","Life of Pi"},
		{"Uptown-4 pm","Silver Lining"},
		{"Bayfield-7 pm","GI Joe"},
		{"Bayfield-2 pm","GI Joe"},
		{"Galaxy-4 pm","Life of Pi"},
		{"Uptown-10 pm","Life of Pi"},
		{"Galaxy-1 pm","Identity Theif"},
		{"Bayfield-5 pm","The Host"},
		{"Galaxy-6 pm","Oblivion"},
		{"Bayfield-10 pm","GI Joe"},
		{"Uptown-5 pm","Identity Theif"},
		{"Uptown-3 pm","Life of Pi"},
		{"Uptown-7 pm","The Host"},
		{"Galaxy-2 pm","The Host"},
		{"Galaxy-9 pm","GI Joe"},
		{"Galaxy-8 pm","The Host"},
		{"Uptown-4 pm","Silver Lining"},
		{"Galaxy-5 pm","Silver Lining"},
		{"Bayfield-8 pm","The Host"},
		{"Galaxy-1 pm","The Host"},
		{"Uptown-1 pm","The Host"},
		{"Uptown-4 pm","Life of Pi"},
		{"Galaxy-4 pm","The Host"},
		{"Uptown-1 pm","Oblivion"},
		{"Galaxy-6 pm","Life of Pi"},
		{"Bayfield-2 pm","Oblivion"},
		{"Galaxy-6 pm","Silver Lining"},
		{"Uptown-6 pm","GI Joe"},
		{"Galaxy-2 pm","The Host"},
		{"Uptown-5 pm","GI Joe"},
		{"Bayfield-9 pm","The Host"},
		{"Bayfield-5 pm","The Host"},
		{"Bayfield-1 pm","Identity Theif"},
		{"Bayfield-2 pm","GI Joe"},
		{"Uptown-1 pm","GI Joe"},
		{"Uptown-10 pm","GI Joe"},
		{"Uptown-5 pm","The Host"}
	};

	return data;
}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtmovie;
    private javax.swing.JTextArea txtoutput;
    // End of variables declaration//GEN-END:variables
}
